# Generated by Django 3.1.2 on 2020-11-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20201115_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='title',
        ),
    ]
